#!/usr/bin/env python3
"""
dns_manager.py -- System-layer script for Vexlyx DNS Zone Management (F3.3).

Generates, validates, and synchronizes RFC 1035 zone files for CoreDNS and BIND9.
Called by the Fastify API or CLI via stdin JSON / args.
Outputs JSON responses on stdout.

Commands:
  sync_zone    -- Generates RFC 1035 zone file and writes to CoreDNS zones directory.
  delete_zone  -- Deletes zone file from CoreDNS zones directory.
  verify_zone  -- Validates zone file syntax.
"""

import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Stream encoding
# ---------------------------------------------------------------------------

if hasattr(sys.stdin, "reconfigure"):
    try:
        sys.stdin.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass


def respond(data: dict) -> None:
    print(json.dumps(data), flush=True)


def get_zones_dir() -> Path:
    candidates = [
        Path.cwd() / "docker" / "coredns" / "zones",
        Path.cwd().parent / "docker" / "coredns" / "zones",
        Path.cwd().parent.parent / "docker" / "coredns" / "zones",
    ]
    for c in candidates:
        if c.exists():
            return c
    # Fallback to creating docker/coredns/zones in cwd
    target = Path.cwd() / "docker" / "coredns" / "zones"
    target.mkdir(parents=True, exist_ok=True)
    return target


def format_zone_content(hostname: str, records: list, options: dict = None) -> str:
    options = options or {}
    domain = hostname.rstrip(".")
    origin = f"{domain}."
    default_ttl = options.get("ttl", 3600)
    ns1 = options.get("ns1", "ns1.vexlyx.com.")
    ns2 = options.get("ns2", "ns2.vexlyx.com.")
    admin_email = options.get("adminEmail", f"hostmaster.{domain}").replace("@", ".")
    if not admin_email.endswith("."):
        admin_email += "."

    now_serial = int(datetime.utcnow().strftime("%Y%m%d01"))
    serial = options.get("serial", now_serial)

    lines = [
        f"; Zone file for {domain}",
        f"; Generated by Vexlyx DNS Manager on {datetime.utcnow().isoformat()}",
        f"$ORIGIN {origin}",
        f"$TTL {default_ttl}",
        "",
        "; SOA Record",
        f"@   IN  SOA {ns1} {admin_email} (",
        f"            {serial} ; Serial (YYYYMMDDnn)",
        f"            7200       ; Refresh (2h)",
        f"            3600       ; Retry (1h)",
        f"            1209600    ; Expire (2w)",
        f"            3600 )     ; Minimum TTL (1h)",
        "",
        "; Nameservers",
        f"@       IN  NS      {ns1}",
        f"@       IN  NS      {ns2}",
        "",
        "; Resource Records",
    ]

    for rec in records:
        name = (rec.get("name") or "@").strip()
        rec_type = (rec.get("type") or "A").upper()
        ttl = rec.get("ttl") or default_ttl
        val = rec.get("value", "").strip()

        padded_name = name.ljust(20)
        padded_ttl = str(ttl).ljust(8)

        if rec_type == "MX":
            prio = rec.get("priority", 10)
            lines.append(f"{padded_name} {padded_ttl} IN  MX    {prio} {val}")
        elif rec_type == "SRV":
            prio = rec.get("priority", 0)
            weight = rec.get("weight", 0)
            port = rec.get("port", 0)
            lines.append(f"{padded_name} {padded_ttl} IN  SRV   {prio} {weight} {port} {val}")
        elif rec_type == "TXT":
            clean_val = val.replace('"', '\\"')
            lines.append(f'{padded_name} {padded_ttl} IN  TXT   "{clean_val}"')
        else:
            lines.append(f"{padded_name} {padded_ttl} IN  {rec_type.ljust(6)} {val}")

    lines.append("")
    return "\n".join(lines)


def cmd_sync_zone(payload: dict) -> None:
    hostname = payload.get("hostname")
    if not hostname:
        respond({"success": False, "error": "Missing hostname parameter"})
        sys.exit(1)

    records = payload.get("records", [])
    options = payload.get("options", {})

    content = format_zone_content(hostname, records, options)
    zones_dir = get_zones_dir()
    clean_host = hostname.rstrip(".").lower()
    zone_file = zones_dir / f"{clean_host}.db"

    try:
        zone_file.write_text(content, encoding="utf-8")
        respond({
            "success": True,
            "path": str(zone_file),
            "recordsCount": len(records),
            "zoneContent": content,
        })
    except Exception as e:
        respond({"success": False, "error": str(e)})
        sys.exit(1)


def cmd_delete_zone(payload: dict) -> None:
    hostname = payload.get("hostname")
    if not hostname:
        respond({"success": False, "error": "Missing hostname parameter"})
        sys.exit(1)

    zones_dir = get_zones_dir()
    clean_host = hostname.rstrip(".").lower()
    zone_file = zones_dir / f"{clean_host}.db"

    if zone_file.exists():
        try:
            zone_file.unlink()
            respond({"success": True, "deleted": True, "path": str(zone_file)})
        except Exception as e:
            respond({"success": False, "error": str(e)})
            sys.exit(1)
    else:
        respond({"success": True, "deleted": False, "message": "Zone file not found"})


def main():
    if len(sys.argv) < 2:
        try:
            data = json.load(sys.stdin)
            cmd = data.get("command")
            payload = data.get("payload", {})
        except Exception as e:
            respond({"success": False, "error": f"Invalid JSON stdin: {e}"})
            sys.exit(1)
    else:
        cmd = sys.argv[1]
        try:
            payload = json.loads(sys.argv[2]) if len(sys.argv) > 2 else {}
        except Exception:
            payload = {}

    if cmd == "sync_zone":
        cmd_sync_zone(payload)
    elif cmd == "delete_zone":
        cmd_delete_zone(payload)
    else:
        respond({"success": False, "error": f"Unknown command: {cmd}"})
        sys.exit(1)


if __name__ == "__main__":
    main()
